title: Anluren's Blog
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
description: This is Anluren's personal blog about programming, technology, and software development.
keywords: blog, programming, technology, software development
author: Anluren
url: https://anluren.github.io

collections:
  featured:
    output: false

exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc:
  ext: adoc
  require_front_matter: true
  liquid: true
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
