
= Anluren's Blog
:showtitle:
:page-title: Anluren's Blog for programming and technology
:page-description: Anluren's personal blog about programming, technology, and software development.
:page-keywords: blog, programming, technology, software development

WARNING: This site is still under construction. I'm still getting familiar with Jekyll and AsciiDoc, so things may change or break as I learn.

I have been a software engineer for many years and have worked on a variety of projects mainly for embedded system with hardware ranging from microcontrollers to large network equipments, participating in all phases of the software development lifecycle. This blog is my personal space to share my thoughts and experiences on programming, technology, and software development.

English isng’t my first language, so please excuse any grammatical errors or awkward phrasing you may encounter in my posts. I’m continually working to improve my writing skills.

Also, I welcome feedback and suggestions from readers. If you have any comments or ideas for future posts, please feel free to reach out to me through the contact information provided on this site.



== Blogroll

Check out my list of recommended blogs: link:blogroll.html[Blogroll]


== C++ Syntax Highlighting Test


[source,cpp,linenums]
----
#include <iostream>

int main() {
  std::cout << "Hello, C++!" << std::endl; // <1>
  return 0; // <2>
}
----

<1> Prints a greeting to the console.
<2> Returns 0 to indicate successful execution.

